-- =====================================================================
-- PROJECT 1 - Channel Health: Snowflake setup
-- Creates the warehouse, database, schemas, 8 empty tables and row-count check
-- =====================================================================

CREATE WAREHOUSE IF NOT EXISTS ANALYTICS_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;   -- cost control
CREATE DATABASE IF NOT EXISTS CHANNEL_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS CHANNEL_ANALYTICS.RAW;     -- raw loaded data
CREATE SCHEMA IF NOT EXISTS CHANNEL_ANALYTICS.MART;    -- business-ready views for Power BI
USE WAREHOUSE ANALYTICS_WH;
USE SCHEMA CHANNEL_ANALYTICS.RAW;

-- ---------- dimensions
CREATE OR REPLACE TABLE DIM_DATE (
  DATE DATE PRIMARY KEY, YEAR INT, QUARTER INT, YEAR_QUARTER STRING, MONTH INT,
  MONTH_NAME STRING, YEAR_MONTH STRING, WEEK_START DATE, DAY_OF_WEEK STRING);

CREATE OR REPLACE TABLE DIM_PRODUCT (
  PART_NUMBER STRING PRIMARY KEY, PRODUCT_FAMILY STRING, END_MARKET STRING,
  LIST_PRICE NUMBER(12,4), LEAD_TIME_WEEKS INT, PACK_QTY INT);

CREATE OR REPLACE TABLE DIM_DISTRIBUTOR (
  DISTRIBUTOR_ID STRING PRIMARY KEY, DISTRIBUTOR_NAME STRING, REGION STRING);

-- ---------- facts
CREATE OR REPLACE TABLE FACT_ORDERS (          -- one row per order line (bookings / sell-in)
  ORDER_ID STRING, LINE_ID INT, DISTRIBUTOR_ID STRING, PART_NUMBER STRING,
  ORDER_DATE DATE, REQUEST_DATE DATE, SCHEDULED_SHIP_DATE DATE,
  ORDER_QTY INT, UNIT_PRICE NUMBER(12,4));

CREATE OR REPLACE TABLE FACT_SHIPMENTS (       -- one row per shipment (lines can ship partially)
  SHIPMENT_ID STRING, ORDER_ID STRING, LINE_ID INT, SHIP_DATE DATE, QTY_SHIPPED INT);

CREATE OR REPLACE TABLE FACT_BILLING (          -- one row per invoice line
  INVOICE_ID STRING, ORDER_ID STRING, LINE_ID INT, INVOICE_DATE DATE,
  QTY_BILLED INT, UNIT_PRICE_BILLED NUMBER(12,4), AMOUNT NUMBER(14,2));

CREATE OR REPLACE TABLE FACT_POS (              -- distributor x part x week (sell-through)
  DISTRIBUTOR_ID STRING, PART_NUMBER STRING, WEEK_START DATE, UNITS_SOLD INT, RESALE_VALUE NUMBER(14,2));

CREATE OR REPLACE TABLE FACT_DIST_INVENTORY (   -- distributor x part x week (end-of-week snapshot)
  DISTRIBUTOR_ID STRING, PART_NUMBER STRING, SNAPSHOT_WEEK DATE, UNITS_ON_HAND INT);

-- after loading: validate row counts (compare to the generator output)
SELECT 'orders' t, COUNT(*) FROM FACT_ORDERS UNION ALL
SELECT 'shipments', COUNT(*) FROM FACT_SHIPMENTS UNION ALL
SELECT 'billing', COUNT(*) FROM FACT_BILLING UNION ALL
SELECT 'pos', COUNT(*) FROM FACT_POS UNION ALL
SELECT 'inventory', COUNT(*) FROM FACT_DIST_INVENTORY;
