-- =====================================================================
-- PROJECT 1 - 8 business questions and data-quality checks with SQL
-- =====================================================================
USE WAREHOUSE ANALYTICS_WH;
USE DATABASE CHANNEL_ANALYTICS;

-- Q1. Is sell-in outpacing sell-through? (quarterly, by distributor)
SELECT DATE_TRUNC('quarter', WEEK_START) AS QTR,
       d.DISTRIBUTOR_NAME,
       SUM(UNITS_SELL_IN)                              AS SELL_IN_UNITS,
       SUM(UNITS_SOLD)                                 AS SELL_THROUGH_UNITS,
       SUM(UNITS_SELL_IN) / NULLIF(SUM(UNITS_SOLD), 0) AS SELL_IN_TO_THROUGH_RATIO   -- > 1 = channel building
FROM MART.VW_CHANNEL_WEEKLY c
JOIN RAW.DIM_DISTRIBUTOR d ON c.DISTRIBUTOR_ID = d.DISTRIBUTOR_ID
GROUP BY 1, 2
ORDER BY 1, 2;

-- Q2. Weeks of inventory: latest week vs 26 weeks earlier, by distributor and family
WITH agg AS (
    SELECT c.WEEK_START, c.DISTRIBUTOR_ID, p.PRODUCT_FAMILY,
           SUM(c.UNITS_ON_HAND) / NULLIF(SUM(c.POS_13WK_AVG), 0) AS WOI
    FROM MART.VW_CHANNEL_WEEKLY c
    JOIN RAW.DIM_PRODUCT p ON c.PART_NUMBER = p.PART_NUMBER
    GROUP BY 1, 2, 3
)
SELECT DISTRIBUTOR_ID, PRODUCT_FAMILY,
       MAX(IFF(WEEK_START = (SELECT MAX(WEEK_START) FROM agg), WOI, NULL))                       AS WOI_NOW,
       MAX(IFF(WEEK_START = (SELECT DATEADD('week', -26, MAX(WEEK_START)) FROM agg), WOI, NULL)) AS WOI_26WK_AGO
FROM agg
GROUP BY 1, 2
ORDER BY WOI_NOW DESC;

-- Q3. Delinquent backlog by product family and aging bucket
SELECT p.PRODUCT_FAMILY, b.AGING_BUCKET,
       COUNT(*)          AS LINES,
       SUM(b.OPEN_VALUE) AS OPEN_VALUE
FROM MART.VW_BACKLOG_CURRENT b
JOIN RAW.DIM_PRODUCT p ON b.PART_NUMBER = p.PART_NUMBER
WHERE b.IS_DELINQUENT
GROUP BY 1, 2
ORDER BY 1, 2;

-- Q4. Quarterly book-to-bill
WITH bk AS (SELECT DATE_TRUNC('quarter', ORDER_DATE)   AS QTR, SUM(BOOKING_VALUE) AS BOOKINGS FROM MART.VW_BOOKINGS GROUP BY 1),
     bl AS (SELECT DATE_TRUNC('quarter', INVOICE_DATE) AS QTR, SUM(AMOUNT)        AS BILLINGS FROM MART.VW_BILLINGS GROUP BY 1)
SELECT COALESCE(bk.QTR, bl.QTR) AS QTR, BOOKINGS, BILLINGS,
       BOOKINGS / NULLIF(BILLINGS, 0) AS BOOK_TO_BILL
FROM bk FULL OUTER JOIN bl ON bk.QTR = bl.QTR
WHERE COALESCE(bk.QTR, bl.QTR) >= '2024-01-01'
ORDER BY 1;

-- Q5. Top 2 distributors by billings in each region, last full quarter (Q2 2026)
WITH rev AS (
    SELECT d.REGION, d.DISTRIBUTOR_NAME, SUM(b.AMOUNT) AS BILLINGS
    FROM MART.VW_BILLINGS b
    JOIN RAW.DIM_DISTRIBUTOR d ON b.DISTRIBUTOR_ID = d.DISTRIBUTOR_ID
    WHERE b.INVOICE_DATE >= '2026-04-01' AND b.INVOICE_DATE < '2026-07-01'
    GROUP BY 1, 2
)
SELECT * FROM rev
QUALIFY DENSE_RANK() OVER (PARTITION BY REGION ORDER BY BILLINGS DESC) <= 2
ORDER BY REGION, BILLINGS DESC;

-- Q6. Month-over-month billings growth
WITH m AS (SELECT DATE_TRUNC('month', INVOICE_DATE) AS MTH, SUM(AMOUNT) AS BILLINGS FROM MART.VW_BILLINGS GROUP BY 1)
SELECT MTH, BILLINGS,
       LAG(BILLINGS) OVER (ORDER BY MTH) AS PREV_MONTH,
       (BILLINGS - LAG(BILLINGS) OVER (ORDER BY MTH)) / NULLIF(LAG(BILLINGS) OVER (ORDER BY MTH), 0) AS MOM_PCT
FROM m ORDER BY MTH;

-- Q7. Forward-looking: projected weeks of inventory 13 weeks out, by distributor
--     projected inventory = on hand + open backlog due in next 13 weeks - 13 weeks of sell-through
WITH latest AS (
    SELECT * FROM MART.VW_CHANNEL_WEEKLY
    QUALIFY ROW_NUMBER() OVER (PARTITION BY DISTRIBUTOR_ID, PART_NUMBER ORDER BY WEEK_START DESC) = 1
),
incoming AS (
    SELECT DISTRIBUTOR_ID, PART_NUMBER, SUM(OPEN_QTY) AS INBOUND_13WK
    FROM MART.VW_BACKLOG_CURRENT
    WHERE SCHEDULED_SHIP_DATE <= DATEADD('week', 13, '2026-06-28'::DATE)
    GROUP BY 1, 2
)
SELECT l.DISTRIBUTOR_ID,
       SUM(l.UNITS_ON_HAND) / NULLIF(SUM(l.POS_13WK_AVG), 0) AS WOI_NOW,
       (SUM(l.UNITS_ON_HAND) + SUM(COALESCE(i.INBOUND_13WK, 0)) - 13 * SUM(l.POS_13WK_AVG))
         / NULLIF(SUM(l.POS_13WK_AVG), 0)                    AS WOI_PROJECTED_13WK
FROM latest l
LEFT JOIN incoming i ON l.DISTRIBUTOR_ID = i.DISTRIBUTOR_ID AND l.PART_NUMBER = i.PART_NUMBER
GROUP BY 1
ORDER BY WOI_PROJECTED_13WK DESC;

-- Q8. Data-quality checks you would automate
SELECT 'orders: duplicate keys' AS CHECK_NAME, COUNT(*) AS FAILURES
FROM (SELECT ORDER_ID, LINE_ID FROM RAW.FACT_ORDERS GROUP BY 1, 2 HAVING COUNT(*) > 1)
UNION ALL
SELECT 'shipments: orphan (no matching order line)', COUNT(*)
FROM RAW.FACT_SHIPMENTS s
WHERE NOT EXISTS (SELECT 1 FROM RAW.FACT_ORDERS o WHERE o.ORDER_ID = s.ORDER_ID AND o.LINE_ID = s.LINE_ID)
UNION ALL
SELECT 'shipments: shipped more than ordered', COUNT(*)
FROM (SELECT s.ORDER_ID, s.LINE_ID, SUM(s.QTY_SHIPPED) q FROM RAW.FACT_SHIPMENTS s GROUP BY 1, 2) s
JOIN RAW.FACT_ORDERS o ON o.ORDER_ID = s.ORDER_ID AND o.LINE_ID = s.LINE_ID
WHERE s.q > o.ORDER_QTY
UNION ALL
SELECT 'pos: negative units', COUNT(*) FROM RAW.FACT_POS WHERE UNITS_SOLD < 0;
